// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SirketlerOdemeler.Data;

#nullable disable

namespace SirketlerOdemeler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250729113343_HaberKayitlari")]
    partial class HaberKayitlari
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SirketlerOdemeler.Models.HaberKayitlar", b =>
                {
                    b.Property<int>("HaberKayitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HaberKayitId"));

                    b.Property<string>("HaberBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaberIcerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HaberKategori")
                        .HasColumnType("int");

                    b.Property<DateTime>("HaberTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("HaberYZ1Yorum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaberYZ2Yorum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaberYZ3Yorum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.HasKey("HaberKayitId");

                    b.HasIndex("KategoriId");

                    b.ToTable("HaberKayitlar");
                });

            modelBuilder.Entity("SirketlerOdemeler.Models.Haberler", b =>
                {
                    b.Property<int>("HaberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HaberId"));

                    b.Property<string>("HaberBaslik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HaberGorsel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaberIcerik")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("HaberYapayZekaYorum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SKod")
                        .HasColumnType("int");

                    b.HasKey("HaberId");

                    b.HasIndex("SKod");

                    b.ToTable("Haberler");
                });

            modelBuilder.Entity("SirketlerOdemeler.Models.HaberlerKategoriler", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("KategoriAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriId");

                    b.ToTable("HaberlerKategoriler");
                });

            modelBuilder.Entity("SirketlerOdemeler.Models.Odemeler", b =>
                {
                    b.Property<int>("OdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdemeId"));

                    b.Property<int>("OdenenTutar")
                        .HasColumnType("int");

                    b.Property<int>("SKod")
                        .HasColumnType("int");

                    b.HasKey("OdemeId");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("SirketlerOdemeler.Models.Sirketler", b =>
                {
                    b.Property<int>("SKod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SKod"));

                    b.Property<string>("SirketAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SKod");

                    b.ToTable("Sirketler");
                });

            modelBuilder.Entity("SirketlerOdemeler.Models.HaberKayitlar", b =>
                {
                    b.HasOne("SirketlerOdemeler.Models.HaberlerKategoriler", "haberkategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("haberkategori");
                });

            modelBuilder.Entity("SirketlerOdemeler.Models.Haberler", b =>
                {
                    b.HasOne("SirketlerOdemeler.Models.Sirketler", "Sirket")
                        .WithMany()
                        .HasForeignKey("SKod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sirket");
                });
#pragma warning restore 612, 618
        }
    }
}
